insert into edificios(version, id,nome,endereco) values (1, 1,'zun capfad','Merormo vifeko nevewof cirip pos wive hetoc bipace zuomiti ki ewepi pizalane kaki evenogepe efazuga gamfow.')
insert into edificios(version, id,nome,endereco) values (1, 2,'capfad dec','Unireja mihzurat ugifu we izohu mien guk uczaho gazenapi cuslemcaw tob vifelitod.')
insert into edificios(version, id,nome,endereco) values (1, 3,'dec bivo','Gofadabi bipa ferab ruduhre wuvohu lakeh binav ipa wo unu dibed ucoju po je oh.')
insert into edificios(version, id,nome,endereco) values (1, 4,'bivo judbilo','Gadejeg cisi atafuca mo potwe wooro sidikmow pifodefe ace wahebar mon cive.')
insert into edificios(version, id,nome,endereco) values (1, 5,'judbilo joraf','Sa umaliwe nowdafde caaw zoje decvafpe abe row tihep meffol liebehiw aziadwa gojo dolseku falagum.')
insert into edificios(version, id,nome,endereco) values (1, 6,'joraf kem','Edbilo anida ucsoje urutac ufisosuj ib wesa cavibu fe avvofwiv gob huv bowvenun jigwernud faw ama taf mu.')
insert into edificios(version, id,nome,endereco) values (1, 7,'kem odeter','Tocez jubpaba bitiho ece elamo dapatda mat ojoviwu ked ofdo wewacu va no po falbajme.')
insert into edificios(version, id,nome,endereco) values (1, 8,'odeter lisohuje','Kidolove ozzis ot wikif huf ozvovac siiluza on pedasnag lut tikmuju febazi.')
insert into edificios(version, id,nome,endereco) values (1, 9,'lisohuje duod','Fenkocte diepo fecek cido siz op sehzu nisan nusoigu fujomu pu sotusu gez zoviwugi onuzih efegabu.')
insert into edificios(version, id,nome,endereco) values (1, 10,'duod nowufpus','Nu kuzku ot gad re uli giise ne ufhehri bur rozhewlam gijdad dilzab luno vawiju badvu wu.')
insert into edificios(version, id,nome,endereco) values (1, 11,'nowufpus kagu','Ocfek verhiit ohfo muwvi cipa lipe mulsob jesufka hevguccip ca lo gusikij kosole de.')
insert into edificios(version, id,nome,endereco) values (1, 12,'kagu fef','To golzovsac ge fuv duha fewafu fekhe emoud rukjaajo pudow soafaopo reguz tugdedhus la pu koddid woknig.')
insert into edificios(version, id,nome,endereco) values (1, 13,'fef derwogi','Fa mob pa cawlodlaf ipudnad jidkoena covtez odidup lu sihucjim monce wi wu pavuj ezijuz hurejub.')
insert into edificios(version, id,nome,endereco) values (1, 14,'derwogi wehovuce','Jefouj ul kam no aw dapbo fuserib kubi fuwlawvi efwo ip jeg kumzije.')
insert into edificios(version, id,nome,endereco) values (1, 15,'wehovuce zamum','Jowo pigak luponire bavpactu ewurenu egatilco vun zidba juwa gamwaho bo ujo oro faketi tifun ogoosvos rarag refjanzu.')
insert into edificios(version, id,nome,endereco) values (1, 16,'zamum dunebuh','Jenivame owri couci ji ibcumgu ug ka rewi dipnoksar seta foad tijleve arguwtud okopetcos takji le ohinok.')
insert into edificios(version, id,nome,endereco) values (1, 17,'dunebuh repiwid','Fuk fadjeje bamuife fo oz mizki nuhut danfeh goldudgu jugziwu ganucaj vukgiwlu ekogo vamu uhmo.')
insert into edificios(version, id,nome,endereco) values (1, 18,'repiwid razuppa','Ob pakec pal iwvedoc hodra amivuf pow dasewih zed nor pabpeh nis vazapmah rashas ilo geifvut petfize.')
insert into edificios(version, id,nome,endereco) values (1, 19,'razuppa kulmenim','Jalir abwu fibsitgel wopo jikudu zejanro sodmutta ni li puomam giwa siolo dugab aviikeja tepkuz jetahak rohboche bun.')
insert into edificios(version, id,nome,endereco) values (1, 20,'kulmenim ib','Dostal ze lovok du sov vib epoipra gib ohpiwa zonga oshujic juzob padav umnahma uk hazuw hais ek.')
insert into edificios(version, id,nome,endereco) values (1, 21,'ib ba','Olmenim bo fo cacjujaw keuc ragpa upmuz get erungu edi ulwece voj buwel rore metzut fi utokif.')
insert into edificios(version, id,nome,endereco) values (1, 22,'ba tohhij','Bicor kikrok soc sew jizmek gukure gicodku sij fe nengis tu jokvad.')
insert into edificios(version, id,nome,endereco) values (1, 23,'tohhij tuvo','Di mozinki pakikja nuvok finofap licba gamane favbaflik bewotzas poihi ako zah geruwnas.')
insert into edificios(version, id,nome,endereco) values (1, 24,'tuvo foga','Wepreize ez lomtu is dofir do til ecaati bo ezauhi rupwuja huzatowit jonobe but nihgeguj.')
insert into edificios(version, id,nome,endereco) values (1, 25,'foga uswuzzub','Obo ofulafi wotvac balfesel gob he oz jet beb tenup febidlur diihim fiozi vorri.')
insert into edificios(version, id,nome,endereco) values (1, 26,'uswuzzub hivwerip','Ta on ogeowelon zelo ug kale numo emobige obli wifdip ekazadaf acume ukico vugdom su ise.')
insert into edificios(version, id,nome,endereco) values (1, 27,'hivwerip gugusu','Zus isunubo jiib ija mu noj segargic gugowo ohehi jer nubezup farlazsud guc wo ifozum amifi fuda ahonewufo.')
insert into edificios(version, id,nome,endereco) values (1, 28,'gugusu zedekak','Suwerip opitdep og neukewal vime doahe gosem kikzab ju gim zuwuvta zilucol zadugwa nauti ciuf hu wi diide.')
insert into edificios(version, id,nome,endereco) values (1, 29,'zedekak ral','Uh jit ozonawoj ofihaz aw nim borubit kuwcabzet sizropma buzmu ikasew suv civa bajek tuen janogap ew.')
insert into edificios(version, id,nome,endereco) values (1, 30,'ral turuhu','Lac kak cezif fecranep cu uro miclih budce ob ihauti ruoh ijibader te tezud bavfi erunuba melgaznew mov.')
insert into edificios(version, id,nome,endereco) values (1, 31,'turuhu omjo','Finulate im no fovto haf se ov si rilcibe woukme olu facpec culna.')
insert into edificios(version, id,nome,endereco) values (1, 32,'omjo rig','Irujud weneglaj mozodjun fuz uri fevawdah jejbujov awfiwo vu jecoh hepu kilujige vujuika vap fuzuba.')
insert into edificios(version, id,nome,endereco) values (1, 33,'rig sicewap','Rahjad hul wu imwo pitmusmi bocbuab to ve koomu hec fewidir lofon jo menegfib jaframcok jenlik.')
insert into edificios(version, id,nome,endereco) values (1, 34,'sicewap fo','Medriaju jekcaki mabtac an zojowe pa ci sivube lupoho jugazuje tobcaz ipeza hagen sonkilow.')
insert into edificios(version, id,nome,endereco) values (1, 35,'fo gegijap','Secir ben newo tuukajal nouv re zitizev zanep kakuh pugos wabta cil zi uzolufew eg ipe gu.')
insert into edificios(version, id,nome,endereco) values (1, 36,'gegijap kuvesa','An rol verbijfa ahweoce ovageow widkezehu unatowgaj hektegwi iwawi luvag suf hemgefid.')
insert into edificios(version, id,nome,endereco) values (1, 37,'kuvesa lapahu','Ha ah tat zuvulhep ka sited hog ukoraoli it geesa ecsihot upuoc zipfebud boges pode zeforeb esuhelud.')
insert into edificios(version, id,nome,endereco) values (1, 38,'lapahu zev','Ajkin fag jesob mobcawrel civuzuz irpol teli ofe egov ezgipgug mo jihka iskih vu migbit ujfonba ad.')
insert into edificios(version, id,nome,endereco) values (1, 39,'zev nabeaga','Be cetiw gorvi es ipihipemo sa lor cev zenen tewigzah ve hezto juzlazhu koolobi ovku newehwit awecuiju ga.')
insert into edificios(version, id,nome,endereco) values (1, 40,'nabeaga kaot','Kusdomisu je rekutfep camgitur lo ikasubun henvul wopik je zi uramaha tabbati ume kij.')
insert into edificios(version, id,nome,endereco) values (1, 41,'kaot tawuctuj','Gi et vo dahbehev kot ekaekjal reok ho zobtusov mi resoji vedotzoc faecu lazu ruunougi zam.')
insert into edificios(version, id,nome,endereco) values (1, 42,'tawuctuj eh','De wijlawdin si fub giwtocvo pobmoj muwogod moc su homa kod codmit we busdowhi.')
insert into edificios(version, id,nome,endereco) values (1, 43,'eh fajjusuz','Cugdupkas is ad gow epucul gupgepog lakdi lap me riroz ac ke nucori fulburmi ku nas te.')
insert into edificios(version, id,nome,endereco) values (1, 44,'fajjusuz pave','Kof ag siruhu ledul do et he fofeg cakumla fizi godkij lo igu puwassag.')
insert into edificios(version, id,nome,endereco) values (1, 45,'pave ispaviw','Dejusuz akhot elsieme lo madki kehir tiskehjud wedav amjates ig kogohsew imcepid naho une hevopmes kevuhuna nueb eco.')
insert into edificios(version, id,nome,endereco) values (1, 46,'ispaviw ha','Cep edjoz itpop mobivtu tobfelu fowhi fivemag casjano teklor ivmewpu ehi jezuag zekaca ribsetwi cefma su.')
insert into edificios(version, id,nome,endereco) values (1, 47,'ha iliat','Wom nuw fagu mer difin bu ug ebenahav ker hiwkine ha aw edowaw cumajpa fepdu aha.')
insert into edificios(version, id,nome,endereco) values (1, 48,'iliat do','Bepen fom ov vejliv ani jar fiscawug fot iwadot foodu ruuzpa gamna.')
insert into edificios(version, id,nome,endereco) values (1, 49,'do wi','Pikageno dog gidcuben lu ekov so ef lab eg gan ol mehmesbu usirallot lifotgu le mapuma.')
insert into edificios(version, id,nome,endereco) values (1, 50,'wi iwage','Ve ano kutenar magtas cahaco oheme ig ne wuwmu loareho ar muk conifuk.')
insert into edificios(version, id,nome,endereco) values (1, 51,'iwage joopoju','Nil sismu camifiz tiatovis doz tiuspam fukugo nozdajne upoim zi irhut jot.')
insert into edificios(version, id,nome,endereco) values (1, 52,'joopoju gojawu','Ifeji joabu fe wusefras dooju sakla ewvekac zez husohbi mof jenoc oznova zaevajad canjekhe be.')
insert into edificios(version, id,nome,endereco) values (1, 53,'gojawu afigoh','Vitob wif oca ifwehlez tigesomi jabwun baj cuab wec azef hisutol ma wic wivibjog zo kaj wuese.')
insert into edificios(version, id,nome,endereco) values (1, 54,'afigoh benom','Weawuesi ujebeule befi jewobemo ro awava egu unesegpi apused delrumne wiak ojtiv uca bekuh.')
insert into edificios(version, id,nome,endereco) values (1, 55,'benom jevakbe','Fimvetim or po vograbti fatcoj iljuddez munuw vuwehsi iv danviedu muv arito ladtaw pekuv emo.')
insert into edificios(version, id,nome,endereco) values (1, 56,'jevakbe darhow','Ho puvriz ipacci kijej fiwecuzi julefo cofcacsim wuljoal upmuri jo biilomah pun luvokfo fobrup tefuse.')
insert into edificios(version, id,nome,endereco) values (1, 57,'darhow dupid','Luakbe api zopvogol sunecami vu ujbaece zugginlof gi deddoogi depnom unupa zo lof uriki wavazo vuduka nit rurisop.')
insert into edificios(version, id,nome,endereco) values (1, 58,'dupid comouc','Bohowpok ot pekhesjad gar ag foroka peepiv kercirfis gerima olofovan jamjaiw lahizeji sicapde eki fidjaf.')
insert into edificios(version, id,nome,endereco) values (1, 59,'comouc igunisi','In fafo ko wajenego pazmehkop wamez zin jekba afpuida motazu haz tevditeg nara patwaw gewviza.')
insert into edificios(version, id,nome,endereco) values (1, 60,'igunisi pe','Vaak jisizcok doapo te zecpup dal cer umsul ozu wet utuci rik zahoizo titvi udom virehniz vasu bezwilah.')
insert into edificios(version, id,nome,endereco) values (1, 61,'pe puk','Judsasag heclafbe bulehibu omo zuve uv ne za tivgiphup vanlebaf wuz lanotiz loarva juzficke zuvbumo ifafi to.')
insert into edificios(version, id,nome,endereco) values (1, 62,'puk vegub','Hum lo ran celbehot usalolok pogpuhlif set mojab gor venoek nuwofgij bosag.')
insert into edificios(version, id,nome,endereco) values (1, 63,'vegub rucwi','Akoverwo pozbawwu hemcor lih bupraloj turmu gi oj ipi fimat az kopocbad.')
insert into edificios(version, id,nome,endereco) values (1, 64,'rucwi agijit','Gif vamacno puweca wowelig iciorepog nozdi udifu humi es zatgaken gu firpoj ohueda dim tabatzuv.')
insert into edificios(version, id,nome,endereco) values (1, 65,'agijit loolu','Acapom macnervar losog numolip nik jes otravso ug ceute ba alaom raeju bapak mirib.')
insert into edificios(version, id,nome,endereco) values (1, 66,'loolu tupwovali','Hismu iglic eso turjopor peca sebeceh ewwakhem docre mofufmen em gij pow ofiwi sojotdi wodobneb.')
insert into edificios(version, id,nome,endereco) values (1, 67,'tupwovali hidge','Tu imwala wuno fefnat nutovvec iho epji puv nejgute zeh ozakepih gebugser line lorihumi.')
insert into edificios(version, id,nome,endereco) values (1, 68,'hidge liowci','Opozunpig pownohve ucator siwvujif sibo nip ged ri ukpe ili pa zobetob fibtaser sauro vehit huvru viz.')
insert into edificios(version, id,nome,endereco) values (1, 69,'liowci vesa','Sagenu fu pajarloc wutku acoh codbe ti wuf zeolo na tib edrestu bi uvotuog fa.')
insert into edificios(version, id,nome,endereco) values (1, 70,'vesa wupikdoh','Ni bakvefap damiwoz higusehi fifwa lonuco binfimos kum zutjus so mibvuku pok villavna wupuciz ira dezwurep gasehij.')
insert into edificios(version, id,nome,endereco) values (1, 71,'wupikdoh dajsiphaj','Ken evi igaih cupas ohe du ibe kikcirfu delato tawidus pig cuolela gulseg hovdutba.')
insert into edificios(version, id,nome,endereco) values (1, 72,'dajsiphaj soofpe','Enimoc fuwokaro po bo ipe sulopa powo coov zon poh bi siehivi catsobfe poro coativib nosihcod fofantub et.')
insert into edificios(version, id,nome,endereco) values (1, 73,'soofpe aruzusjas','Fesiphaj vak ju mesde lofo cedrocec dudagu kiev sa him isnetep tasnoz hebjebzoh jonhukis ribbiz fowmemig nis mopocit.')
insert into edificios(version, id,nome,endereco) values (1, 74,'aruzusjas ufeco','Abubi mo duc lecisiteg jinupod ho ficam kup pocov ow rebzakfe zecofup bokuas ularucom pewcapar evcu.')
insert into edificios(version, id,nome,endereco) values (1, 75,'ufeco uneehi','Wusiso wu jepebmav hitip rapoci jebba mo cenwuze fu maluzgih fipojab guzo jawow unitiij ba gufjakat subodpa wojun.')
insert into edificios(version, id,nome,endereco) values (1, 76,'uneehi hahinaba','Gefak puza sethe gikju du ci di hatum ardopbaf pa tuk rad zunobi hedon lag wedtoser.')
insert into edificios(version, id,nome,endereco) values (1, 77,'hahinaba zun','Sezjik tihume jacet ganfune sebap kocug arda lelov anuv ig ap di kemwipu tidbu ra hezwasci.')
insert into edificios(version, id,nome,endereco) values (1, 78,'zun jo','Fimi bajisvu tuhwendaf hepuaz isini muanoku tovgaac jupjifmi pepah jigapkuc ge pebe jorep wuwuzme numepham nu bonuv rajum.')
insert into edificios(version, id,nome,endereco) values (1, 79,'jo goltuefo','Enohov jad we odatode icujutwe esifuj pehriwku kadij fowsejoz luwarine fudor ero.')
insert into edificios(version, id,nome,endereco) values (1, 80,'goltuefo lupuwuzo','Vu muhkid aw ug necnav isho rufmisneh hekrucha wabo dom fapeplu ado nugliw.')
insert into edificios(version, id,nome,endereco) values (1, 81,'lupuwuzo reduzris','Wituefo imzo ropcevbil vohi ewe hauz tarowumu tijacih cahu ruk wikgus ter afaemi ca zezzuc ginit nuzi.')
insert into edificios(version, id,nome,endereco) values (1, 82,'reduzris pubsav','Apuwu ted jape tu odukoho ruzicuk cuvaw po sitvat ambilhu za bonhohav bojmuk fudopin zodtavur dohkibpuw di ce.')
insert into edificios(version, id,nome,endereco) values (1, 83,'pubsav lullip','Kud onijipihe soco jiddirjob jijovo jugzopdid litaf ap jeozi favozti kuw omhi gudgivabu hapal zuzuka wate bulreg uczazev.')
insert into edificios(version, id,nome,endereco) values (1, 84,'lullip aba','Ubsavtef mivnunu hub so soso ni negjalhoj donzijol elufofif enuig ro fukmuhi nu lotil.')
insert into edificios(version, id,nome,endereco) values (1, 85,'aba kettujwo','Elliprej gibic kug sufigi gugute idijuniwa oh ipo menafco awip ruweli bebwezji vuhkaw puh rictinpih.')
insert into edificios(version, id,nome,endereco) values (1, 86,'kettujwo ju','Bavducma kesatki huco evuok juhe howfisew sovvo totuv iw beme nu zi.')
insert into edificios(version, id,nome,endereco) values (1, 87,'ju vioburez','Kutujwo dav kiokha hoj ti zigo laz jeetgiv viz dopimad fapuvaona cafutrus mokomdu rujkip gewvuvi renses ollimil.')
insert into edificios(version, id,nome,endereco) values (1, 88,'vioburez ig','Itpa di emezeku avrozuk he ak adu nato limekmuk zic luj muut.')
insert into edificios(version, id,nome,endereco) values (1, 89,'ig omu','Ruw une wofbihuhu aj teh wib zudi hulvorgi ju mah ehe howdugoh ag ron ris onuiwovu soemro.')
insert into edificios(version, id,nome,endereco) values (1, 90,'omu luw','Jad koh we uzjaf zutaahi ete zapsaata epa siwofimi bivses mor ulnasok haj.')
insert into edificios(version, id,nome,endereco) values (1, 91,'luw pi','Rudjow lunebuh geor kecliddoc po bihdar urtuvuh ipimaad dujlec tufu fuzvuvkob ije ruurilor.')
insert into edificios(version, id,nome,endereco) values (1, 92,'pi zu','Ewmosa napo fomwahe mojdal ujo me kakin ti emgolbo ekupoc uhzuwfe zeha.')
insert into edificios(version, id,nome,endereco) values (1, 93,'zu ag','Sa we vu wetutook do ve gebiig ciemgil hiz ge jokasu vus gofona.')
insert into edificios(version, id,nome,endereco) values (1, 94,'ag fopav','Urube lis fuknurif jetvic cowonwap pincozfiz dig gockoda ase hovoc keehe itafej.')
insert into edificios(version, id,nome,endereco) values (1, 95,'fopav ji','Jek roule jijpep sojzo fa hetjo bac reowe fuwjajo jup sagava nezwiba.')
insert into edificios(version, id,nome,endereco) values (1, 96,'ji lojet','Toavleg mibgo vumvega hohtif muwubfag af ge benefi baod jor ho si jake dofdo.')
insert into edificios(version, id,nome,endereco) values (1, 97,'lojet ukve','Ma wu akusimjuv epecekco don lo japo uzuerohu cipeh gi toz ihu.')
insert into edificios(version, id,nome,endereco) values (1, 98,'ukve viipo','Aphu vih tipco pouwo uvoli direftag jemce cesakno kaz zudvat suvha zu avi ucopefke.')
insert into edificios(version, id,nome,endereco) values (1, 99,'viipo apuwibem','Map uravo saclefi ce jowoka velrakho dutbur suz rabcuwe gapero paz jejlo mivji dueta ih.')
insert into edificios(version, id,nome,endereco) values (1, 100,'apuwibem nine','Ruw bofzeg gen daitpuw egom mus gi uglet nufdip fosowa jigjufe ruczal rom sis jaj.')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 1,'70','70','70','jigrormo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 2,'11','11','11','zun')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 3,'51','51','51','capfad')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 4,'11','11','11','dec')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 5,'53','53','53','bivo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 6,'87','87','87','judbilo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 7,'58','58','58','joraf')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 8,'15','15','15','kem')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 9,'66','66','66','odeter')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 10,'79','79','79','lisohuje')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 11,'42','42','42','duod')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 12,'82','82','82','nowufpus')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 13,'67','67','67','kagu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 14,'16','16','16','fef')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 15,'95','95','95','derwogi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 16,'75','75','75','wehovuce')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 17,'50','50','50','zamum')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 18,'75','75','75','dunebuh')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 19,'92','92','92','repiwid')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 20,'91','91','91','razuppa')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 21,'74','74','74','kulmenim')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 22,'10','10','10','ib')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 23,'29','29','29','ba')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 24,'50','50','50','tohhij')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 25,'37','37','37','tuvo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 26,'58','58','58','foga')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 27,'89','89','89','uswuzzub')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 28,'91','91','91','hivwerip')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 29,'77','77','77','gugusu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 30,'95','95','95','zedekak')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 31,'15','15','15','ral')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 32,'51','51','51','turuhu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 33,'66','66','66','omjo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 34,'32','32','32','rig')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 35,'80','80','80','sicewap')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 36,'10','10','10','fo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 37,'79','79','79','gegijap')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 38,'84','84','84','kuvesa')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 39,'95','95','95','lapahu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 40,'33','33','33','zev')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 41,'69','69','69','nabeaga')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 42,'36','36','36','kaot')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 43,'83','83','83','tawuctuj')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 44,'30','30','30','eh')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 45,'90','90','90','fajjusuz')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 46,'60','60','60','pave')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 47,'67','67','67','ispaviw')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 48,'6','6','6','ha')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 49,'66','66','66','iliat')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 50,'15','15','15','do')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 51,'10','10','10','wi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 52,'47','47','47','iwage')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 53,'81','81','81','joopoju')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 54,'36','36','36','gojawu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 55,'51','51','51','afigoh')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 56,'53','53','53','benom')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 57,'96','96','96','jevakbe')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 58,'57','57','57','darhow')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 59,'53','53','53','dupid')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 60,'88','88','88','comouc')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 61,'83','83','83','igunisi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 62,'7','7','7','pe')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 63,'14','14','14','puk')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 64,'55','55','55','vegub')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 65,'43','43','43','rucwi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 66,'52','52','52','agijit')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 67,'43','43','43','loolu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 68,'75','75','75','tupwovali')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 69,'55','55','55','hidge')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 70,'76','76','76','liowci')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 71,'41','41','41','vesa')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 72,'97','97','97','wupikdoh')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 73,'89','89','89','dajsiphaj')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 74,'69','69','69','soofpe')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 75,'87','87','87','aruzusjas')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 76,'61','61','61','ufeco')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 77,'66','66','66','uneehi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 78,'95','95','95','hahinaba')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 79,'12','12','12','zun')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 80,'23','23','23','jo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 81,'85','85','85','goltuefo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 82,'94','94','94','lupuwuzo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 83,'97','97','97','reduzris')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 84,'43','43','43','pubsav')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 85,'51','51','51','lullip')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 86,'12','12','12','aba')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 87,'85','85','85','kettujwo')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 88,'10','10','10','ju')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 89,'79','79','79','vioburez')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 90,'24','24','24','ig')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 91,'22','22','22','omu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 92,'5','5','5','luw')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 93,'16','16','16','pi')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 94,'4','4','4','zu')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 95,'11','11','11','ag')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 96,'34','34','34','fopav')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 97,'2','2','2','ji')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 98,'37','37','37','lojet')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 99,'55','55','55','ukve')
insert into apartamentos(version, id,numero,andar,metragem,situacao) values (1, 100,'53','53','53','viipo')
insert into moradores(version, id,nome,cpf,telefone) values (1, 1,'zun capfad','67242','(762) 526-5961')
insert into moradores(version, id,nome,cpf,telefone) values (1, 2,'capfad dec','16795','(267) 955-5124')
insert into moradores(version, id,nome,cpf,telefone) values (1, 3,'dec bivo','59016','(680) 368-2192')
insert into moradores(version, id,nome,cpf,telefone) values (1, 4,'bivo judbilo','19120','(281) 301-2039')
insert into moradores(version, id,nome,cpf,telefone) values (1, 5,'judbilo joraf','50051','(600) 616-7955')
insert into moradores(version, id,nome,cpf,telefone) values (1, 6,'joraf kem','88281','(882) 813-1374')
insert into moradores(version, id,nome,cpf,telefone) values (1, 7,'kem odeter','54266','(642) 665-1763')
insert into moradores(version, id,nome,cpf,telefone) values (1, 8,'odeter lisohuje','19335','(383) 458-2132')
insert into moradores(version, id,nome,cpf,telefone) values (1, 9,'lisohuje duod','67913','(769) 335-6771')
insert into moradores(version, id,nome,cpf,telefone) values (1, 10,'duod nowufpus','70348','(803) 586-8035')
insert into moradores(version, id,nome,cpf,telefone) values (1, 11,'nowufpus kagu','43191','(531) 919-2280')
insert into moradores(version, id,nome,cpf,telefone) values (1, 12,'kagu fef','82466','(814) 667-8937')
insert into moradores(version, id,nome,cpf,telefone) values (1, 13,'fef derwogi','61311','(713) 311-8766')
insert into moradores(version, id,nome,cpf,telefone) values (1, 14,'derwogi wehovuce','19122','(381) 421-2371')
insert into moradores(version, id,nome,cpf,telefone) values (1, 15,'wehovuce zamum','95026','(940) 463-7299')
insert into moradores(version, id,nome,cpf,telefone) values (1, 16,'zamum dunebuh','78723','(777) 435-9570')
insert into moradores(version, id,nome,cpf,telefone) values (1, 17,'dunebuh repiwid','41719','(517) 393-9630')
insert into moradores(version, id,nome,cpf,telefone) values (1, 18,'repiwid razuppa','71190','(711) 904-3669')
insert into moradores(version, id,nome,cpf,telefone) values (1, 19,'razuppa kulmenim','93520','(935) 404-4792')
insert into moradores(version, id,nome,cpf,telefone) values (1, 20,'kulmenim ib','93516','(935) 267-8492')
insert into moradores(version, id,nome,cpf,telefone) values (1, 21,'ib ba','77394','(763) 948-4815')
insert into moradores(version, id,nome,cpf,telefone) values (1, 22,'ba tohhij','03804','(238) 240-2561')
insert into moradores(version, id,nome,cpf,telefone) values (1, 23,'tohhij tuvo','21005','(410) 257-1723')
insert into moradores(version, id,nome,cpf,telefone) values (1, 24,'tuvo foga','46672','(566) 726-3346')
insert into moradores(version, id,nome,cpf,telefone) values (1, 25,'foga uswuzzub','31690','(416) 906-7221')
insert into moradores(version, id,nome,cpf,telefone) values (1, 26,'uswuzzub hivwerip','51161','(611) 712-1562')
insert into moradores(version, id,nome,cpf,telefone) values (1, 27,'hivwerip gugusu','81978','(919) 887-8542')
insert into moradores(version, id,nome,cpf,telefone) values (1, 28,'gugusu zedekak','99258','(982) 684-7650')
insert into moradores(version, id,nome,cpf,telefone) values (1, 29,'zedekak ral','71193','(811) 931-8202')
insert into moradores(version, id,nome,cpf,telefone) values (1, 30,'ral turuhu','93730','(927) 400-3928')
insert into moradores(version, id,nome,cpf,telefone) values (1, 31,'turuhu omjo','16514','(365) 345-1498')
insert into moradores(version, id,nome,cpf,telefone) values (1, 32,'omjo rig','56696','(656) 968-9869')
insert into moradores(version, id,nome,cpf,telefone) values (1, 33,'rig sicewap','63951','(739) 612-6585')
insert into moradores(version, id,nome,cpf,telefone) values (1, 34,'sicewap fo','39542','(485) 521-2687')
insert into moradores(version, id,nome,cpf,telefone) values (1, 35,'fo gegijap','74552','(835) 620-3330')
insert into moradores(version, id,nome,cpf,telefone) values (1, 36,'gegijap kuvesa','02175','(211) 851-5960')
insert into moradores(version, id,nome,cpf,telefone) values (1, 37,'kuvesa lapahu','72121','(811) 311-5257')
insert into moradores(version, id,nome,cpf,telefone) values (1, 38,'lapahu zev','84383','(843) 836-3759')
insert into moradores(version, id,nome,cpf,telefone) values (1, 39,'zev nabeaga','91303','(913) 235-1856')
insert into moradores(version, id,nome,cpf,telefone) values (1, 40,'nabeaga kaot','37738','(467) 487-7239')
insert into moradores(version, id,nome,cpf,telefone) values (1, 41,'kaot tawuctuj','62414','(724) 340-3634')
insert into moradores(version, id,nome,cpf,telefone) values (1, 42,'tawuctuj eh','31302','(413) 229-8428')
insert into moradores(version, id,nome,cpf,telefone) values (1, 43,'eh fajjusuz','89609','(886) 292-9749')
insert into moradores(version, id,nome,cpf,telefone) values (1, 44,'fajjusuz pave','21837','(418) 472-1239')
insert into moradores(version, id,nome,cpf,telefone) values (1, 45,'pave ispaviw','87113','(961) 233-3461')
insert into moradores(version, id,nome,cpf,telefone) values (1, 46,'ispaviw ha','50502','(605) 226-4037')
insert into moradores(version, id,nome,cpf,telefone) values (1, 47,'ha iliat','61976','(719) 765-1705')
insert into moradores(version, id,nome,cpf,telefone) values (1, 48,'iliat do','03202','(232) 228-5539')
insert into moradores(version, id,nome,cpf,telefone) values (1, 49,'do wi','66845','(768) 554-8377')
insert into moradores(version, id,nome,cpf,telefone) values (1, 50,'wi iwage','11163','(311) 731-7079')
insert into moradores(version, id,nome,cpf,telefone) values (1, 51,'iwage joopoju','00745','(207) 554-6244')
insert into moradores(version, id,nome,cpf,telefone) values (1, 52,'joopoju gojawu','46891','(558) 913-2855')
insert into moradores(version, id,nome,cpf,telefone) values (1, 53,'gojawu afigoh','84265','(832) 759-6654')
insert into moradores(version, id,nome,cpf,telefone) values (1, 54,'afigoh benom','39273','(482) 736-8079')
insert into moradores(version, id,nome,cpf,telefone) values (1, 55,'benom jevakbe','57714','(677) 345-2680')
insert into moradores(version, id,nome,cpf,telefone) values (1, 56,'jevakbe darhow','51027','(610) 374-7581')
insert into moradores(version, id,nome,cpf,telefone) values (1, 57,'darhow dupid','99238','(982) 583-8067')
insert into moradores(version, id,nome,cpf,telefone) values (1, 58,'dupid comouc','59006','(680) 266-3167')
insert into moradores(version, id,nome,cpf,telefone) values (1, 59,'comouc igunisi','51195','(611) 955-4652')
insert into moradores(version, id,nome,cpf,telefone) values (1, 60,'igunisi pe','84061','(940) 714-8088')
insert into moradores(version, id,nome,cpf,telefone) values (1, 61,'pe puk','87828','(868) 481-5125')
insert into moradores(version, id,nome,cpf,telefone) values (1, 62,'puk vegub','02529','(225) 395-2772')
insert into moradores(version, id,nome,cpf,telefone) values (1, 63,'vegub rucwi','17583','(365) 837-6888')
insert into moradores(version, id,nome,cpf,telefone) values (1, 64,'rucwi agijit','50625','(606) 352-8734')
insert into moradores(version, id,nome,cpf,telefone) values (1, 65,'agijit loolu','45580','(555) 800-7339')
insert into moradores(version, id,nome,cpf,telefone) values (1, 66,'loolu tupwovali','56725','(657) 357-3671')
insert into moradores(version, id,nome,cpf,telefone) values (1, 67,'tupwovali hidge','42368','(523) 789-5485')
insert into moradores(version, id,nome,cpf,telefone) values (1, 68,'hidge liowci','77696','(766) 966-7387')
insert into moradores(version, id,nome,cpf,telefone) values (1, 69,'liowci vesa','58251','(672) 613-2954')
insert into moradores(version, id,nome,cpf,telefone) values (1, 70,'vesa wupikdoh','71344','(803) 549-9387')
insert into moradores(version, id,nome,cpf,telefone) values (1, 71,'wupikdoh dajsiphaj','42633','(526) 435-1819')
insert into moradores(version, id,nome,cpf,telefone) values (1, 72,'dajsiphaj soofpe','94785','(937) 855-5936')
insert into moradores(version, id,nome,cpf,telefone) values (1, 73,'soofpe aruzusjas','87013','(960) 335-6192')
insert into moradores(version, id,nome,cpf,telefone) values (1, 74,'aruzusjas ufeco','63570','(735) 809-2611')
insert into moradores(version, id,nome,cpf,telefone) values (1, 75,'ufeco uneehi','86779','(857) 797-7918')
insert into moradores(version, id,nome,cpf,telefone) values (1, 76,'uneehi hahinaba','66923','(659) 331-1543')
insert into moradores(version, id,nome,cpf,telefone) values (1, 77,'hahinaba zun','65963','(759) 639-8597')
insert into moradores(version, id,nome,cpf,telefone) values (1, 78,'zun jo','94215','(942) 352-4854')
insert into moradores(version, id,nome,cpf,telefone) values (1, 79,'jo goltuefo','15786','(247) 867-8287')
insert into moradores(version, id,nome,cpf,telefone) values (1, 80,'goltuefo lupuwuzo','20269','(302) 793-9936')
insert into moradores(version, id,nome,cpf,telefone) values (1, 81,'lupuwuzo reduzris','86174','(861) 740-6628')
insert into moradores(version, id,nome,cpf,telefone) values (1, 82,'reduzris pubsav','96386','(953) 866-9992')
insert into moradores(version, id,nome,cpf,telefone) values (1, 83,'pubsav lullip','91539','(915) 491-8384')
insert into moradores(version, id,nome,cpf,telefone) values (1, 84,'lullip aba','49490','(584) 909-6235')
insert into moradores(version, id,nome,cpf,telefone) values (1, 85,'aba kettujwo','58384','(673) 849-4256')
insert into moradores(version, id,nome,cpf,telefone) values (1, 86,'kettujwo ju','17800','(268) 208-9643')
insert into moradores(version, id,nome,cpf,telefone) values (1, 87,'ju vioburez','88338','(873) 489-6641')
insert into moradores(version, id,nome,cpf,telefone) values (1, 88,'vioburez ig','04387','(243) 974-5539')
insert into moradores(version, id,nome,cpf,telefone) values (1, 89,'ig omu','71659','(816) 699-1291')
insert into moradores(version, id,nome,cpf,telefone) values (1, 90,'omu luw','21920','(319) 401-1090')
insert into moradores(version, id,nome,cpf,telefone) values (1, 91,'luw pi','25959','(359) 691-6408')
insert into moradores(version, id,nome,cpf,telefone) values (1, 92,'pi zu','08389','(273) 892-4646')
insert into moradores(version, id,nome,cpf,telefone) values (1, 93,'zu ag','10451','(304) 610-2881')
insert into moradores(version, id,nome,cpf,telefone) values (1, 94,'ag fopav','04796','(237) 969-2900')
insert into moradores(version, id,nome,cpf,telefone) values (1, 95,'fopav ji','10722','(207) 424-6468')
insert into moradores(version, id,nome,cpf,telefone) values (1, 96,'ji lojet','39166','(481) 661-8179')
insert into moradores(version, id,nome,cpf,telefone) values (1, 97,'lojet ukve','01241','(212) 510-3444')
insert into moradores(version, id,nome,cpf,telefone) values (1, 98,'ukve viipo','34376','(433) 862-3076')
insert into moradores(version, id,nome,cpf,telefone) values (1, 99,'viipo apuwibem','51940','(619) 506-4452')
insert into moradores(version, id,nome,cpf,telefone) values (1, 100,'apuwibem nine','52658','(616) 688-6883')
